# Generated by Django 3.1 on 2020-08-21 09:04

from django.db import migrations, models
import django_mysql.models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='food_seasoning',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=[], max_length=220, size=20),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='food_ingredient',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
