# Generated by Django 3.1 on 2020-08-25 08:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='food_ingredient',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
