# Generated by Django 3.1 on 2020-08-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200826_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
