# Generated by Django 3.1 on 2020-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
