# Generated by Django 3.1 on 2020-08-30 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=20)),
                ('food_seasoning', django_mysql.models.ListCharField(models.CharField(max_length=10), default=True, max_length=220, size=20)),
                ('food_ingredient', jsonfield.fields.JSONField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
