# Generated by Django 3.1 on 2020-08-17 14:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('food_seasoning', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=220, size=20)),
                ('food_ingredient', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
