# Generated by Django 3.1 on 2020-08-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_ingredient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='food_ingredient',
            field=models.JSONField(),
        ),
    ]
