# Generated by Django 3.1 on 2020-08-19 11:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_auto_20200818_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='food_ingredient',
            field=jsonfield.fields.JSONField(),
        ),
    ]
