# Generated by Django 3.1 on 2020-08-17 13:36

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('food_ingredient', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('picture', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
    ]
