# Generated by Django 3.1 on 2020-08-19 12:03

from django.db import migrations, models
import django_mysql.models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('food_seasoning', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=220, size=20)),
                ('food_ingredient', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recipe',
        ),
    ]
