# Generated by Django 3.1 on 2020-08-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0002_auto_20200819_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
