# Generated by Django 3.1 on 2020-08-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0002_auto_20200819_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
