<<<<<<< HEAD
# Generated by Django 3.1 on 2020-08-23 04:41
=======
# Generated by Django 3.1 on 2020-08-21 12:32
>>>>>>> 4c52e637aaa359d98f8fd2689e9aa2dec4b2334f

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0002_auto_20200819_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
